# Generated by Django 2.2.12 on 2021-05-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_matches', models.TextField(max_length=250)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Playersinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/')),
                ('jersey_nmbr', models.IntegerField()),
                ('counry', models.CharField(max_length=150)),
                ('matches', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('high_score', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('hundres', models.IntegerField()),
                ('player_type', models.CharField(max_length=250)),
            ],
        ),
    ]
