# Generated by Django 3.1.7 on 2021-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='media/')),
                ('club_state', models.CharField(max_length=150)),
            ],
        ),
    ]
