# Generated by Django 3.1.7 on 2021-05-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0003_auto_20210515_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matches_points',
            new_name='Matchespoints',
        ),
        migrations.RenameModel(
            old_name='Playersinfo',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='Team_info',
            new_name='Team',
        ),
    ]
