# Generated by Django 3.1.7 on 2021-05-16 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0004_auto_20210515_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='counry',
            new_name='country',
        ),
    ]
