# Generated by Django 3.1.7 on 2021-05-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0005_auto_20210516_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team1_score', models.IntegerField(blank=True, max_length=50, null=True)),
                ('team2_score', models.IntegerField(blank=True, max_length=50, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='cricketapp.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='cricketapp.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Matchespoints',
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(upload_to='media1/'),
        ),
    ]
